-- MySQL Script generated by MySQL Workbench
-- Mon Apr 15 17:01:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema sitiosturisticos
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estados` (
  `estado_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `capital` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`estado_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sitios_vacacionales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sitios_vacacionales` (
  `sitiosvacacionales_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `lat` FLOAT(10,2) NULL DEFAULT 0000000000.00,
  `long` FLOAT(10,2) NULL DEFAULT 0000000000.00,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `direccion` VARCHAR(400) NULL,
  PRIMARY KEY (`sitiosvacacionales_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`media`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`media` (
  `media_id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(100) NULL,
  `descripcion` VARCHAR(45) NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`media_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lugares_de_interes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lugares_de_interes` (
  `lugaresdeinteres_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` TEXT NULL,
  `costopromedio` VARCHAR(45) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`lugaresdeinteres_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`valoraciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`valoraciones` (
  `valoraciones_id` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(45) NULL,
  `calificacion` VARCHAR(45) NULL,
  PRIMARY KEY (`valoraciones_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
